<div id="searchContainer">
    <div class="topsearch">
        <form action="" id="formSearchVideo">
            <input type="text" id="query" placeholder="Buscan Cancion aqui">
            <button> <i class="fa fa-search"></i> </button>
        </form>
    </div>
    <div id="resultSearch">
        <ul>
        </ul>
    </div>
</div>
<div id="playerContainer">
    <div id="ytPlayer">
        <video id="ytVideo"></video>
        <div class="ytControls">
            <a href="#play" id="ytPlay"><i class="fa fa-play"></i></a>
            <a href="#pause" id="ytPause"><i class="fa fa-pause"></i></a>
        </div>
        <div id="ytLoading"><i class="fa fa-circle-o-notch fa-spin"></i></div>
    </div>
</div>